import { Layout } from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import bannerImg from "@/../public/images/profile/developer-pic-1.png";
import { AnimatedText } from '@/components/AnimatedText';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>The Virtual Reality of Tasbih Ahmed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={bannerImg} alt="Chowdhury Tasbih Ahmed Siddique" className="w-full h-auto" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="text-5xl text-left"
              />
              <p className="my-4 text-base font-medium">As a skilled junior MERN Stack developer, I am dedicated to turning ideas into innovative web applications. Explore my latest projects and articles, showcasing my expertise in MERN Stack technologies and web development.
                <br />
                Stay up to date with me and my portfolio.</p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/Resume.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >Resume</Link>

                <Link
                  href="mailto:ctasbihas@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                >Contact by Email</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
