export const allProjects = [
	{
		id: 1,
		title: "ZipRide",
		description:
			"ZipRide is a production-grade, fully responsive, and role-based ride booking platform inspired by Uber and Pathao. Built with React, Redux Toolkit, and RTK Query, it delivers tailored experiences for Riders, Drivers, and Admins, ensuring a polished, intuitive, and consistent UI/UX across all devices.",
		longDescription: "",
		technologies: ["React", "Node.js", "MongoDB", "SSL Commerz", "Redux"],
		image: "/api/placeholder/600/400",
		liveUrl: "https://zipride.vercel.app/",
		githubUrl: "https://github.com/ctasbihas/zipride_frontend",
		category: "Full Stack",
		date: "2025-08",
		featured: true,
		status: "In Progress",
	},
	{
		id: 2,
		title: "Doctors Portal",
		description:
			"Doctors Portal is a web application for booking medical appointments and managing schedules. Built with React and Firebase, it offers real-time updates, secure authentication, and a user-friendly interface for both patients and doctors.",
		longDescription: "",
		technologies: ["React", "Firebase", "Daisy UI", "React Router"],
		image: "/api/placeholder/600/400",
		liveUrl: "https://doctors-portal-48670.web.app/",
		githubUrl: "https://github.com/ctasbihas/doctors-portal-client",
		category: "Full Stack",
		date: "2023-12",
		featured: true,
		status: "Completed",
	},
	{
		id: 3,
		title: "Librium",
		description:
			"The Minimal Library Management System is a client-side app built with React, Redux Toolkit Query (RTK Query), and TypeScript. No user authentication — just pure focus on core library functionalities like book management & borrowing.",
		longDescription: "",
		technologies: ["React"],
		image: "/api/placeholder/600/400",
		liveUrl: "https://mylibrium.vercel.app",
		githubUrl: "https://github.com/ctasbihas/librium",
		category: "Full Stack",
		date: "2025-07",
		featured: true,
		status: "Completed",
	},
	{
		id: 4,
		title: "Bistro Buzz",
		description:
			"Bistro Buzz is an online restaurant platform for browsing menus, placing orders, and tracking deliveries. It offers a seamless experience for customers to discover restaurants, customize orders, and enjoy fast, reliable food delivery.",
		longDescription:
			"Bistro Buzz streamlines the online food ordering process with an intuitive interface, real-time order tracking, and secure payment options. Customers can explore a variety of restaurants, view detailed menus, and personalize their orders. The platform supports advanced search, location-based recommendations, and integrates with popular payment gateways for a hassle-free dining experience.",
		technologies: ["React", "Redux", "Node.js", "Express.js", "MongoDB"],
		image: "",
		category: "Full Stack",
		date: "2023-10",
		liveUrl: "https://bistrobuzz.vercel.app/",
		githubUrl: "https://github.com/ctasbihas/bistrobuzz-client",
		featured: false,
		status: "Completed",
	},
	{
		id: 5,
		title: "Picta",
		description:
			"Picta is a modern Instagram clone featuring photo sharing, user profiles, likes, comments, and real-time updates. Built with a responsive design and smooth animations, it delivers a familiar social media experience.",
		longDescription:
			"Picta replicates core Instagram functionalities, allowing users to upload photos, follow others, like and comment on posts, and view interactive feeds. The platform emphasizes performance, accessibility, and user experience, with real-time notifications, optimized image handling, and seamless navigation across devices.",
		technologies: ["React", "Tailwind CSS", "App write", "TypeScript"],
		image: "",
		category: "Frontend",
		date: "2023-09",
		liveUrl: "https://picta-phi.vercel.app/",
		githubUrl: "https://github.com/ctasbihas/picta",
		featured: false,
		status: "In Progress",
	},
	{
		id: 6,
		title: "Blue Collar",
		description:
			"Blue Collar is a simple car mechanic landing page designed to showcase services, expertise, and contact information for automotive repair businesses.",
		longDescription:
			"This landing page provides an overview of car mechanic services, highlights key offerings, and includes easy-to-access contact details. The clean and professional design helps automotive businesses attract customers and establish an online presence.",
		technologies: ["Next.js", "MongoDB", "Stripe"],
		image: "",
		category: "Full Stack",
		date: "2023-08",
		liveUrl: "https://bluecollar.vercel.app/",
		githubUrl: "https://github.com/ctasbihas/bluecollar",
		featured: false,
		status: "Completed",
	},
	{
		id: 7,
		title: "Food Express Go",
		description:
			"Food Express Go is an online restaurant platform for browsing menus, placing orders, and tracking deliveries. It offers a seamless experience for customers to discover restaurants, customize orders, and enjoy fast, reliable food delivery.",
		longDescription:
			"Food Express Go streamlines the online food ordering process with an intuitive interface, real-time order tracking, and secure payment options. Customers can explore a variety of restaurants, view detailed menus, and personalize their orders. The platform supports advanced search, location-based recommendations, and integrates with popular payment gateways for a hassle-free dining experience.",
		technologies: ["Next.js", "MongoDB", "Stripe", "Cloudinary"],
		image: "",
		category: "Full Stack",
		date: "2023-08",
		liveUrl: "https://foodexpressgo.vercel.app/",
		githubUrl: "https://github.com/ctasbihas/FoodExpressGo",
		featured: false,
		status: "Completed",
	},
];
